In [ ]:
#importing NumPy
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
#List to NumPy Array
my_np_arr = np.array(
    [1,2,3]
)

print(my_np_arr)
print(type(my_np_arr))
print(my_np_arr.dtype)
print(my_np_arr.shape)
print(my_np_arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [ ]:
#Fill an array with a certain size
a = np.zeros(
    shape = (5,)
)
a


array([0., 0., 0., 0., 0.])

In [ ]:
#Fill an array with a certain value and size and data type
one = np.ones(
    shape = (10,2),
    dtype = 'int'
)
one

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#Fill an array with a certain value and size
assigned_with_specific_np_array = np.full(
    shape=(10,),
    fill_value = 15,
)
assigned_with_specific_np_array

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [ ]:
#identity matrix in NumPy
id_matrix = np.eye(4)
print(id_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Creating a random empty NumPy Array
random_a = np.empty(
    shape=(5,),
    dtype = int
)
random_a

array([0, 0, 0, 0, 0])

In [ ]:
#List to NumPy Array
list = [1,2,3]
npArray = np.array(
    list
)
npArray

array([1, 2, 3])

In [ ]:
#TypeCast
print(npArray.dtype)
newType = npArray.astype('float')
newType.dtype

int64


dtype('float64')

In [ ]:
#np.ar1 = np.arrange(start=1,stop=11, step=1)
ar1 = np.arange(1,11)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#linespace
ar2 = np.linspace(
    start=0,
    stop=10,
    num=9
)
ar2

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
'''
 NumPy Array dimensions
 -scaler ->00
 -vector -->10
 --Matrix -->20
 --Tensor -->xD where x>2

 Tensor is a unit data type of PyTorch and Tensorflow
'''
#Scaler Array
scaler = np.array(47)
#1D Array
oneD = np.array([47, 23, 35, 00])
print(scaler)
print(oneD)
twoD = np.array([[47, 23, 35, 00],[47, 23, 35, 00],[47, 23, 35, 00]])
print(twoD)
print(twoD[1,1])

47
[47 23 35  0]
[[47 23 35  0]
 [47 23 35  0]
 [47 23 35  0]]
23


In [ ]:
print(twoD[0:2,0:3])

[[47 23 35]
 [47 23 35]]


In [ ]:
#nD Array
nDarr = np.zeros(
    shape=(5,3,2,2)
)
nDarr


array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [ ]:
#indexing
listx = [1,2,3]
print(listx[-1])
print(listx[1 ])

3
2


In [ ]:
#Selecting a SubArray
aa=np.array(
    [1,2,3,4,5]
)

print(aa[1:4])
print(aa[0:4:2])

[2 3 4]
[1 3]
