In [ ]:
""" Class 2. Numpy Methods

Objectives:
1. iterate over a numpy array
2. useful methods: reshape, sort, argmin, argmax, dot, split, mean, median etc.
3. different techniques to filter elements from a numpy array
4. vectorization
5. broadcasting
"""

In [ ]:
"""A cell can be two types:
1. Code
2. Markdown
"""

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
np_array = np.array(
    [1, 2, 3, 4]
)

for val in np_array:
  print(val)

1
2
3
4


In [ ]:
for i in range(len(np_array)):
  print(np_array[i])

1
2
3
4


In [ ]:
for i, val in enumerate(np_array):
  print (f"index = {i}, value = {val}")

index = 0, value = 1
index = 1, value = 2
index = 2, value = 3
index = 3, value = 4


In [ ]:
#NUMPY METHOD

In [ ]:
#Reshape
twoD = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9],
     [10, 11, 12]]
)

newTwoD = twoD.reshape(3,4)
print(newTwoD)

threeD = np.array(
    [[[1,2,3],
     [4,5,6],
     [7,8,9],
     [10, 11, 12]],
     [[1,2,3],
     [4,5,6],
     [7,8,9],
     [10, 11, 12]],
     [[1,2,3],
     [4,5,6],
     [7,8,9],
     [10, 11, 12]]]
)

print(threeD.reshape(1,6,-1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]


In [ ]:
#Sorting
b = np.array(
    [1, 2, 53, 35, 6, 10]
)
print(np.sort(b))
print(np.sort(b)[::-1])

[ 1  2  6 10 35 53]
[53 35 10  6  2  1]


In [3]:
#arg Max and arg Min
prob = np.array(
    [.2, .3, .1, .7]
)

indxMax = np.argmax(prob)
print(indxMax)
indxMin = np.argmin(prob)
print(indxMin)

3
2


In [ ]:
#Split

c = np.split(
    b,
    indices_or_sections= 3
)
print(c)

[array([1, 2]), array([53, 35]), array([ 6, 10])]


In [ ]:
#Dot Product
d = np.array(
    [[2,1,4],
     [2,0,8],
     [1,3,4]]
)
e = np.dot(d, d)
print(e)
print("-----0-----")
#Transpose
print(e.T)

[[10 14 32]
 [12 26 40]
 [12 13 44]]
-----0-----
[[10 12 12]
 [14 26 13]
 [32 40 44]]


In [ ]:
print(np.mean(e))
print(np.median(e))
print(np.std(e))

22.555555555555557
14.0
12.517641871562365


In [ ]:
#Numpy Filtering

In [ ]:
#1.Boolean Mask
p = np.array(
    [1, 2, 3, 4, 10]
)

filter_mask = [True, False, True, False, True]
f_arr = p[filter_mask]
print(f_arr)

[ 1  3 10]


In [ ]:
#2.Conditional
fm = (p%2 ==1)
f_arr2 = p[fm]
print(f_arr2)

[1 3]


In [ ]:
#3.Indices
indices = [0, 1, 4]
farr3 = p[indices]
print(farr3)


[ 1  2 10]


In [ ]:
#custom filter method
def f_arr(x):
  if x%2 == 0:
    return False
  return True

fI = filter(f_arr, p)
g = np.array(
    list(fI)
)
g

array([1, 3])

In [ ]:
#Vectorization
vector = np.array(
    [1, 2, 3, 4, 5]
)

print(vector %2==0)
print(vector+5)

[False  True False  True False]
[ 6  7  8  9 10]


In [ ]:
#Broadcasting
w = np.array(
    [[1,2],
    [1,2],
    [1,2]]
)

x = np.array(
    [[1, 2],
    [3,4],
    [5,6]]
)

print(w*x)

y= np.array(
    [1,2]
)

print(x+y)
print(w*y)

[[ 1  4]
 [ 3  8]
 [ 5 12]]
[[2 4]
 [4 6]
 [6 8]]
[[1 4]
 [1 4]
 [1 4]]
