In [1]:
 #importing NumPy
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
arr = np.zeros(
    shape = (2,3,2)
)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [22]:
#First Dimension: axis = 0
#Second Dimension: axis = 1
#...
#Nth Dimension: axix = N-1

#Aggregation function: sum, min, max, meadian

arr1 = np.array(
    [
    [
            [1,2,3],
            [4,5,6]
      ],

     [
          [1,2,3],
          [4,5,6]
     ],

     [    [1,2,3],
          [4,5,6]
      ],
    [    [1,2,3],
          [4,5,6]
      ]
      ]
)

print(np.sum(arr1[0]))
print(np.sum(arr1))
print(np.sum(arr1, axis= 2))

21
84
[[ 6 15]
 [ 6 15]
 [ 6 15]
 [ 6 15]]


In [24]:
#Numpy Random
'''
'''

print(np.random.rand())
print(np.random.rand(2,5))

0.8423821544218497
[[0.38172193 0.6511635  0.50497284 0.23911172 0.1055702 ]
 [0.31586047 0.50651435 0.20937455 0.88456088 0.71174316]]


In [28]:
print(np.random.randint(100))
print(np.random.randint(100, size = (2,5)))

72
[[37 88 75 37 13]
 [27 30 17 49 23]]


In [32]:
#random shuffle
array = [1,4,3, 29,22]
a = np.array(
    array
)
np.random.shuffle(a)
print(a)

[29  3  1 22  4]


In [37]:
'''

ML: Data -> Model -> Training
Example = Dataset -> Training Dataset
Test Dataset
Validation Dataset


'''

dataSet = np.random.randint(100, size=(1000,5))
print("Dataset: \n", dataSet[:5])
np.random.shuffle(dataSet)
print(dataSet[:5])


Dataset: 
 [[50 60 20 88 47]
 [22 73  7 52 49]
 [11 81 72 36  8]
 [74  8 83 98 46]
 [88 20 80 27 66]]
[[44 13 69 58 63]
 [66  5 97 59 46]
 [35 80 50 47 30]
 [28 87  0  3 42]
 [65 47 85 73 37]]


In [38]:
indx1 = int(.8*len(dataSet))
indx2 = int(.9*len(dataSet))

trainset, valset, testset = np.split(
    dataSet,
    [indx1, indx2],
)

print(len(trainset), len(valset), len(testset))

800 100 100
